### ISSUE TITLE
Setup subreddit error

### ISSUE THREAD

**Issue by ghost** [kleiton0x00/RedditC2#3]
RedditC2> set subreddit redditc2
Traceback (most recent call last):
  File "teamserver.py", line 158, in <module>
    if(sub_exists(command[14:])):
  File "teamserver.py", line 53, in sub_exists
    reddit.subreddits.search_by_name(sub, exact=True)
  File "/usr/local/lib/python3.8/dist-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/praw/models/subreddits.py", line 146, in search_by_name
    result = self._reddit.post(
  File "/usr/local/lib/python3.8/dist-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/praw/reddit.py", line 842, in post
    return self._objectify_request(
  File "/usr/local/lib/python3.8/dist-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/usr/local/lib/python3.8/dist-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/usr/local/lib/python3.8/dist-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/usr/local/lib/python3.8/dist-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/usr/local/lib/python3.8/dist-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/usr/local/lib/python3.8/dist-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.8/dist-packages/prawcore/auth.py", line 425, in refresh
    self._request_token(
  File "/usr/local/lib/python3.8/dist-packages/prawcore/auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by kleiton0x00** [comment]
It could be one these issues: 
- Please make sure that your **username/password/client id/client secret** is correctly pasted in **config.json** (Note: Remember that the username is your reddit's account name, not the bot's name.).  
- Did you manually create a new private subreddit named **redditc2** (if no, please create it manually in Reddit before using the `set subreddit redditc2` command)?
- Is the User Agent in **config.json** a legit one?

**Comment by kleiton0x00** [comment]
Closing the issue due to inactivity.
